# Generated by Django 6.0 on 2025-12-18 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('boyi', models.FloatField(default=0, help_text='Olcham metrda (masalan: 23,4)')),
                ('vitrina', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Parda',
                'verbose_name_plural': 'Pardalar',
            },
        ),
        migrations.CreateModel(
            name='PardaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='parda_images/')),
                ('parda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parda.parda')),
            ],
        ),
        migrations.CreateModel(
            name='RulonKusok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curtain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='parda.parda')),
            ],
        ),
    ]
