# Generated by Django 6.0 on 2025-12-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pardaimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parda_images/'),
        ),
    ]
